name: "Upload to Steam Workshop"

on:
  - push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AnarkisGaming/workshop@v1
        with:
          appID: 394360
          publishedFileID: 2843237571
        env:
          STEAM_ACCOUNT_NAME: ${{ secrets.STEAM_ACCOUNT_NAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}